### ISSUE TITLE
Complete DAY1 intro to AI/ML slides

### ISSUE THREAD

**Issue by AleksCipri** [BNL-Fermi-Summer-School-2023/tutorials#10]

**Comment by AleksCipri** [comment]
https://docs.google.com/presentation/d/1rTdhyjryut-woPliMeRFvXEILXpHkM_O_Q_Pz5nY2FI/edit?usp=sharing

**Comment by matthewcarbone** [comment]
@AleksCipri so the idea here is that this is basically the first ~30 minutes of substantive content the students see on Day 1 correct?

**Comment by AleksCipri** [comment]
Yes. So this is before they start working on setting up Colab and other initial hands-on activities. We can spend some time to introduce ourselves and talk about some introductory AI concepts and terms. You can also add some intro related to your lab into this if you want to share how AI is used in your research

**Comment by matthewcarbone** [comment]
@AleksCipri Marking as done. Feel free to reopen if necessary.
