### ISSUE TITLE
Complete DAY 6 CNN intro slides

### ISSUE THREAD

**Issue by AleksCipri** [BNL-Fermi-Summer-School-2023/tutorials#11]

**Comment by AleksCipri** [comment]
Done: https://docs.google.com/presentation/d/1GUPf2pCBxNch-KI--KSnxFP8LmAiqSc0HZLOeavULQw/edit?usp=sharing

**Comment by matthewcarbone** [comment]
This is awesome content, I think we'll definitely steal this for one of our later days. 👍

**Comment by matthewcarbone** [comment]
@AleksCipri Marking as done. Free free to reopen if necessary!
