### ISSUE TITLE
Complete the DNN tutorial first draft

### ISSUE THREAD

**Issue by matthewcarbone** [BNL-Fermi-Summer-School-2023/tutorials#12]

**Comment by matthewcarbone** [comment]
@ben-hawks at this stage it would be really helpful to have an open PR! Would that be possible? I have a BNL volunteer who will want to take a look. Thanks!

**Comment by matthewcarbone** [comment]
@ben-hawks just following up on this. Thanks! 👍

**Comment by matthewcarbone** [comment]
@ben-hawks @AleksCipri @voetberg All what's going on with the DNN tutorial? We need a PR as soon as possible, I want to give the BNL team some time to review. Thanks!

**Comment by ben-hawks** [comment]
Finalized the DNN Notebook in #26! (minor tweaks/extra context mostly)
