### ISSUE TITLE
Normal and Noisy Distribution in introduction.ipynb

### ISSUE THREAD

**Issue by hagha7** [BNL-Fermi-Summer-School-2023/tutorials#18]
After creating the noise and adding the noise and normal distribution together, the assert function to test the mean comparison gives back an error. The (noisy_normal_distribution.mean() > normal_distribution.mean() - .1) and (noisy_normal_distribution.mean() < normal_distribution.mean() + .1) should not compare by a .1 difference, but perhaps with a .25 difference with the addition of upper bound and/or lower bound values.

**Comment by voetberg** [comment]
Ah, I thought I fixed this before. Good catch. Putting in a pr shortly.
